SELECT
    "A1"."FIRSTNAME"     "FIRSTNAME",
    "A1"."SURNAME"       "SURNAME",
    "A1"."EMAIL"         "EMAIL",
    "A1"."COMPANYNAME"   "COMPANYNAME"
FROM
    "YELLOWCOM2"."CREDITACCOUNT_T" "A1"
WHERE
    "A1"."SERVICEACCESSED" IS NOT NULL


(SELECT
    "A1"."MODELNAME"   "MODELNAME",
    "A1"."ALGOTYPE"    "ALGOTYPE",
    "A1"."TRAINDS"     "TRAINDS",
    "A1"."ACCURACY"    "ACCURACY",
    "A1"."DATECREAT"   "DATECREAT",
    "A1"."AVAIL"       "AVAIL",
    "A1"."PRICE"       "PRICE"
FROM
    "YELLOWCOM2"."PRETRAINED_T" "A1"
WHERE
    "A1"."CURRENTHIST"."DOC" IS NULL
)
UNION ALL
(SELECT
    "A1"."MODELNAME"   "MODELNAME",
    "A1"."ALGOTYPE"    "ALGOTYPE",
    "A1"."TRAINDS"     "TRAINDS",
    "A1"."ACCURACY"    "ACCURACY",
    "A1"."DATECREAT"   "DATECREAT",
    "A1"."AVAIL"       "AVAIL",
    "A1"."PRICE"       "PRICE"
FROM
    "YELLOWCOM2"."DEPLOYED_T" "A1"
WHERE
    "A1"."CURRENTHIST"."DOC" IS NULL
);


( SELECT
    "A3"."MODELNAME"        "MODELNAME",
    "A3"."ALGOTYPE"         "ALGOTYPE",
    "A3"."TRAINDS"          "TRAINDS",
    "A3"."ACCURACY"         "ACCURACY",
    "A3"."DATECREAT"        "DATECREAT",
    "A3"."AVAIL"            "AVAIL",
    "A3"."PRICE"            "PRICE",
    "A3"."HIGHLIGHTTABLE"   "HIGHLIGHTTABLE",
    "A3"."EXPLAINATION"     "EXPLAINATION",
    "A3"."CURRENTHIST"      "CURRENTHIST"
FROM
    "YELLOWCOM2"."DEPLOYED_T" "A3"
WHERE
    EXISTS (
        SELECT
            "A5"."KEYFEAT" "KEYFEAT"
        FROM TABLE(A3.HIGHLIGHTTABLE) A5
        WHERE
            "A5"."NESTED_TABLE_ID" = "A3"."SYS_NC0001100012$"
            AND "A5"."KEYFEAT" < 10
    )
)
UNION ALL
( SELECT
    "A2"."MODELNAME"        "MODELNAME",
    "A2"."ALGOTYPE"         "ALGOTYPE",
    "A2"."TRAINDS"          "TRAINDS",
    "A2"."ACCURACY"         "ACCURACY",
    "A2"."DATECREAT"        "DATECREAT",
    "A2"."AVAIL"            "AVAIL",
    "A2"."PRICE"            "PRICE",
    "A2"."HIGHLIGHTTABLE"   "HIGHLIGHTTABLE",
    "A2"."EXPLAINATION"     "EXPLAINATION",
    "A2"."CURRENTHIST"      "CURRENTHIST"
FROM
    "YELLOWCOM2"."PRETRAINED_T" "A2"
WHERE
    EXISTS (
        SELECT
            "A7"."KEYFEAT" "KEYFEAT"
        FROM TABLE(A2.HIGHLIGHTTABLE) A7
        WHERE
            "A7"."NESTED_TABLE_ID" = "A2"."SYS_NC0001100012$"
            AND "A7"."KEYFEAT" < 10
    )
);


( SELECT
    "A5"."MODELNAME"    "MODELNAME",
    "A4"."KEYFEAT"      "KEYFEAT",
    "A4"."DATAPREPR"    "DATAPREPR",
    "A4"."KEYINSIGHT"   "KEYINSIGHT"
FROM
    "YELLOWCOM2"."DEPLOYED_T"             "A5",
    TABLE (A5.HIGHLIGHTTABLE)   A4
WHERE
    "A4"."NESTED_TABLE_ID" = "A5"."SYS_NC0001100012$" AND
    "A5"."ACCURACY" = 1
)
UNION ALL
( SELECT
    "A3"."MODELNAME"    "MODELNAME",
    "A2"."KEYFEAT"      "KEYFEAT",
    "A2"."DATAPREPR"    "DATAPREPR",
    "A2"."KEYINSIGHT"   "KEYINSIGHT"
FROM
    "YELLOWCOM2"."PRETRAINED_T"           "A3",
    TABLE (A3.HIGHLIGHTTABLE)   A2
WHERE
    "A2"."NESTED_TABLE_ID" = "A3"."SYS_NC0001100012$" AND
    "A3"."ACCURACY" = 1
);

